workflows:
  version: 2
  main:
    jobs:
      - build
      # - deploy-staging:
      #    requires:
      #      - build
      #    filters:
      #      branches:
      #        ignore: master
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    steps:
      - checkout
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public

  deploy:
    docker:
      - image: cibuilds/hugo
    steps:
      - attach_workspace:
          at: src
      - run: |
          cd public && git add --all && git commit -m "Publishing to gh-pages (publish.sh)" && cd ..
          git push upstream gh-pages