version: 2.1

executors:
  hugo:
    docker:
      - image: circleci/hugo
    working_directory: ~/project/portail

jobs:
  import:
    executor: hugo
    steps:
      - checkout
      - attach_workspace:
          at: '~/project/portail'
      - run: 
          name: "Import startups and people data from beta.gouv.fr"
          command: ./import_from_betagouv.sh
      - persist_to_workspace:
          root: '~'
          paths:
            - project/betagouv    
            - project/portail      
  build:
    executor: hugo
    steps:
      - checkout
      - attach_workspace:
          at: '~/project/portail'
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/docs --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: '~'
          paths:
            - project/portail/src/docs
  deploy:
    executor: hugo
    steps:
      - attach_workspace:
          at: '~/project/portail/src'
      - add_ssh_keys:
          fingerprints:
            - "96:42:b8:98:23:ad:5b:3a:97:db:ac:1c:33:5a:57:00"
      - run: |
          rm -rf docs
          mv src/docs .
          git config credential.helper 'cache --timeout=120'
          git config user.email "<circleci>"
          git config user.name "CircleCi"
          status=$(git status -s)
          empty=''
          if [ "$status" = "$empty" ]; then 
            echo "Pas de modifications dans docs. Pas de deploy."
            exit 0
          else
            git add .
            git commit -m "Update site from circleci" -m "[ci skip]"
            git push origin master
          fi
workflows:
  weekly-import:
    triggers:
      - schedule: 
        cron: "0 0 * * 0" # every sunday
    jobs:
      - import:
          filters:
            branches:
              only: master
  main:
    jobs:
      - import
      - build:
          requires:
            - import
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master