version: 2.1

executors:
  hugo:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project/portail

jobs:
  import:
    executor: hugo
    environment: 
      LIST_RESULTS: /tmp/list-results
      BETAGOUV: /tmp/betagouv
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/portail
      - run: mkdir -p $LIST_RESULTS
      - run: mkdir -p $BETAGOUV
      - run: git clone https://github.com/betagouv/beta.gouv.fr.git $BETAGOUV
      - run: 
          name: List mtes startups from beta.gouv.fr
          command: cd $BETAGOUV/content/_startups && grep -rl "mtes" > $LIST_RESULTS/startups.txt
      - run: 
          name: List MTES authors from beta.gouv.fr
          command: cd $BETAGOUV/content/_authors && grep -rl "MTES" > $LIST_RESULTS/authors.txt
      - run: 
          name: List authors by mtes startup
          command: |
            while read -r line; do
              startup_file="$line"
              IFS='.'
              read -ra ADDR \<\<\< "$startup_file"
              i=0
              for startup in "${ADDR[@]}"; do
                if [ "$i" == 0 ]; then
                  find $BETAGOUV/content/_authors -type f -name *.md | xargs grep -rl "$startup" >>  $LIST_RESULTS/authors.txt
                  i=$(( i + 1 ))
                fi
              done
              IFS=' ' 
            done < $LIST_RESULTS/startups.txt
      - run:
          name: Remove startup md files in repo
          command: |
              cd src/content/startup
              mv _index.md _index.md.bak
              find . -type f -name *.md -delete
              mv _index.md.bak _index.md
      - run:
          name: Copy startups from betagouv to startup in repo
          command: |
              while read -r line; do
                cp "$line" src/content/startup
              done < $LIST_RESULTS/startups.txt
      - run:
          name: Remove people md files in repo
          command: |
              cd src/content/people
              mv _index.md _index.md.bak
              find . -type f -name *.md -delete
              mv _index.md.bak _index.md
      - run:
          name: Copy authors from betagouv to people in repo
          command: |
              while read -r line; do
                cp "$line" src/content/people
              done < $LIST_RESULTS/startups.txt
      - run:
          name: Deploy to repo
          command: bash deploy_to_repo.sh
      - store_artifacts:
          path: /tmp/list-results
          destination: raw-list-results
  build:
    executor: hugo
    steps:
      - checkout
      - run:
          name: Build Website With Hugo
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: Test Website
          command: htmlproofer src/docs --allow-hash-href --check-html --empty-alt-ignore --disable-external  
      - run:
          name: Deploy to repo
          command: bash deploy_to_repo.sh
workflows:
  version: 2
  weekly-import:
    triggers:
      - schedule: 
          cron: "0 0 * * 0" # every sunday
          filters:
            branches:
              only: master
    jobs:
      - import:
          filters:
            branches:
              only: master
  main:
    jobs:
      - import
      - build:
          requires:
            - import
          filters:
            branches:
              only: master