workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    steps:
      - checkout
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/docs --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - docs

  deploy:
    docker:
      - image: cibuilds/hugo
    steps:
      - checkout
      - attach_workspace:
          at: src
      - add_ssh_keys:
          fingerprints:
            - "96:42:b8:98:23:ad:5b:3a:97:db:ac:1c:33:5a:57:00"
      - run: |
          rm -rf docs
          mv src/docs .
          git config credential.helper 'cache --timeout=120'
          git config user.email "<circleci>"
          git config user.name "CircleCi"
          status=$(git status -s)
          empty=''
          if [ "$status" = "$empty" ]; then 
            echo "Pas de modifications dans docs. Pas de deploy."
            exit 0
          else
            git add .
            git commit -m "Update site from circleci" -m "[ci skip]"
            git push origin master
          fi