version: 2.1

executors:
  hugo:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project/portail

jobs:
  import:
    executor: hugo
    steps:
      - checkout
      - run: 
          name: "Import startups and people data from beta.gouv.fr"
          command: bash export_from_betagouv.sh
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: artifacts
          paths:
            - startups
            - authors
      - deploy:
          command: |
            echo "Deploy import from beta.gouv.fr"
  build:
    executor: hugo
    steps:
      - checkout
      - attach_workspace:
          at: artifacts
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/docs --allow-hash-href --check-html --empty-alt-ignore --disable-external  
      - deploy:
          command: |
            rm -rf docs
            mv src/docs .
workflows:
  version: 2
  weekly-import:
    triggers:
      - schedule: 
          cron: "0 0 * * 0" # every sunday
          filters:
            branches:
              only: master
    jobs:
      - import:
          filters:
            branches:
              only: master
  main:
    jobs:
      - import
      - build:
          requires:
            - import
          filters:
            branches:
              only: master