baseURL = "https://mtes-mct.github.io/portail/"
languageCode = "fr-FR"
title = "La fabrique numérique du pôle ministériel de la transition écologique et de la cohésion des territoires et des relations avec les collectivités territoriales"
theme = "fabnum"
publishDir = "docs"